#region Copyright & License Information
/*
 * Copyright 2007-2021 The OpenRA Developers (see AUTHORS)
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using OpenRA.Traits;

namespace OpenRA.Mods.Common.Traits
{
	[TraitLocation(SystemActors.Player)]
	[Desc("Reveals the entire map to this player while enabled by a condition.",
		"Unlike `" + nameof(RevealsShroud) + "` this is a player-level trait with no position and no",
		"per-tick work: it registers a single shroud source covering every projected cell on enable and",
		"drops it again on disable, so the cost is one pass over the map per on/off transition no matter",
		"how many actors are responsible for the condition.",
		"Note that map exploration is permanent in OpenRA: disabling this restores fog of war over the",
		"whole map, but terrain uncovered while it was active stays uncovered.")]
	public class RevealsMapOnConditionInfo : ConditionalTraitInfo
	{
		[Desc("Can this reveal shroud generated by the `" + nameof(CreatesShroud) + "` trait?")]
		public readonly bool RevealGeneratedShroud = true;

		public override object Create(ActorInitializer init) { return new RevealsMapOnCondition(this); }
	}

	public class RevealsMapOnCondition : ConditionalTrait<RevealsMapOnConditionInfo>
	{
		readonly Shroud.SourceType sourceType;

		Shroud shroud;
		bool revealing;

		public RevealsMapOnCondition(RevealsMapOnConditionInfo info)
			: base(info)
		{
			sourceType = info.RevealGeneratedShroud ? Shroud.SourceType.Visibility : Shroud.SourceType.PassiveVisibility;
		}

		// Player.Shroud is not assigned until after the player actor's Created callbacks have run,
		// so resolve the trait off the player actor itself rather than going via self.Owner.
		Shroud GetShroud(Actor self)
		{
			if (shroud == null)
				shroud = self.Trait<Shroud>();

			return shroud;
		}

		protected override void TraitEnabled(Actor self)
		{
			if (revealing)
				return;

			// Map.ProjectedCells is already a cached PPos[] owned by the map, so this allocates nothing.
			GetShroud(self).AddSource(this, sourceType, self.World.Map.ProjectedCells);
			revealing = true;
		}

		protected override void TraitDisabled(Actor self)
		{
			if (!revealing)
				return;

			GetShroud(self).RemoveSource(this);
			revealing = false;
		}
	}
}
