name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - bleed
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux (.NET 6.0)
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Clone Repository
        uses: actions/checkout@v7

      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '6.0.x'

      - name: Install Lua 5.1
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1

      - name: Check Code
        run: make check

      - name: Check Scripts
        run: make check-scripts

      - name: Check Mods
        run: make test

      - name: Run Unit Tests
        run: >-
          dotnet test OpenRA.Test/OpenRA.Test.csproj
          --configuration Debug
          --nologo
          -p:TargetPlatform=linux-x64

  windows:
    name: Windows (.NET 6.0)
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - name: Clone Repository
        uses: actions/checkout@v7

      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '6.0.x'

      - name: Install Lua 5.1
        shell: pwsh
        run: |
          choco install lua --version=5.1.5.52 -y
          "C:\Program Files (x86)\Lua\5.1" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check Code
        shell: pwsh
        run: .\make.ps1 check

      - name: Check Scripts
        shell: pwsh
        run: .\make.ps1 check-scripts

      - name: Check Mods
        shell: pwsh
        run: .\make.ps1 test

      - name: Run Unit Tests
        shell: pwsh
        run: >-
          dotnet test OpenRA.Test\OpenRA.Test.csproj
          --configuration Debug
          --nologo
          -p:TargetPlatform=win-x64
